/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsernameImport } from './routes/$username'
import { Route as IndexImport } from './routes/index'
import { Route as UserPostPostIdImport } from './routes/$user.post.$postId'

// Create/Update Routes

const UsernameRoute = UsernameImport.update({
  path: '/$username',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserPostPostIdRoute = UserPostPostIdImport.update({
  path: '/$user/post/$postId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$username': {
      preLoaderRoute: typeof UsernameImport
      parentRoute: typeof rootRoute
    }
    '/$user/post/$postId': {
      preLoaderRoute: typeof UserPostPostIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  UsernameRoute,
  UserPostPostIdRoute,
])

/* prettier-ignore-end */
